/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Example: typeof import('./src/components/example.vue')['default']
    VCard: typeof import('vuetify/components')['VCard']
  }
}
